url: "https://mangapress.github.io"
baseurl: "/documentation"

title: Manga+Press Documentation

# Short description of your site
description: Documentation for using and developing for Manga+Press

header-img:

link-normal:
link-visited:
# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""
# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""
title-separator: "-"

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: markdown
highlighter: rouge

# Exclude these files from production site
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
- developer-api