url: "https://mangapress.github.io"
baseurl: "/documentation"

title: Manga+Press Documentation

# Short description of your site
description: Documentation for using and developing for Manga+Press

header-img:

link-normal:
link-visited:
# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""
# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""
title-separator: "-"

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1

defaults:
-
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "default"

# Exclude these files from production site
exclude:
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile